### ISSUE TITLE
Doesn't work when installed properly on macOS

### ISSUE THREAD

**Issue by goodevilgenius** [goodevilgenius/droplogger#40]
## Expected Behavior
When installed on macOS, should work as expected.

## Current Behavior
```
Traceback (most recent call last):
  File "/usr/local/bin/droplogger", line 11, in <module>
    load_entry_point('droplogger==1.0', 'console_scripts', 'droplogger')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 587, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2800, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2431, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2441, in resolve
    raise ImportError(str(exc))
ImportError: 'module' object has no attribute 'main'
```

Similar output for `drop-a-log`

## Possible Solution
⁉

## Steps to Reproduce
1. `cd path/to/droplogger`
2. `pip install .` or `python setup.py install`
3. `droplogger -h` or `drop-a-log -h`
4. 😭

## Environment
- macOS 10.13.3
- pip 9.0.1
- system-installed python 2.7.10
- Homebrew 1.5.10
- Python 2.7.14 (installed through `brew`)
- Python 3.6.4 (installed through `brew`)

## Workaround

I managed to get it working by symlinking both scripts in `path/to/repo/scripts` in my `$PATH`.

**Comment by goodevilgenius** [comment]
It seems that on systems where it installs to site-packages, it fails, but when installed to dist-packages, it works fine.
